<html xmlns:string="xalan://java.lang.String" xmlns:lxslt="http://xml.apache.org/xslt">
<head>
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Unit Test Results: All Errors</title>
<link rel="stylesheet" type="text/css" title="Style" href="stylesheet.css">
</head>
<body onload="open('allclasses-frame.html','classListFrame')">
<h1>Unit Test Results.</h1>
<table width="100%">
<tr>
<td align="left"></td><td align="right">Designed for use with <a href="http://www.junit.org/">JUnit</a> and <a href="http://ant.apache.org/">Ant</a>.</td>
</tr>
</table>
<hr size="1">
<h2>All Errors</h2>
<table class="details" border="0" cellpadding="5" cellspacing="2" width="95%">
<tr valign="top">
<th>Class</th><th>Name</th><th>Status</th><th width="80%">Type</th><th nowrap>Time(s)</th>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testCrearLugarF"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testCrearLugarF">testCrearLugarF</a></td><td>Error</td><td>org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'lugar' for key 'Nombre'"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'lugar' for key 'Nombre'"<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:275)<br>	at edu.uag.iidis.scec.pruebas.LugarDAOTest.testCrearLugarF(LugarDAOTest.java:75)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'lugar' for key 'Nombre'"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:104)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeUpdate(Unknown Source)<br>	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2849)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3290)<br>	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:80)<br>	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:273)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:265)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:186)<br>	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:323)<br>	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52)<br>	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1081)<br>	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:315)<br>	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)<br>	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175)<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:266)<br>Caused by: java.sql.SQLException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'lugar' for key 'Nombre'"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1741)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1588)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.063</td>
</tr>
</table>
</body>
</html>
